spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://165.229.86.152:9500/MOONKEY?serverTimezone=UTC&characterEncoding=UTF-8
    password: newoop0510

  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        format_sql: 'true'
    database: mysql
    hibernate:
      ddl-auto: update

jwt:
  header: Authorization
  # HS512 알고리즘 사용하므로 64byte 이상의 secret key를 사용해야 함. base64? ???? ?
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400 # 초
